-- MySQL Script generated by MySQL Workbench
-- Mon Jun 17 19:54:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_ManageHR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ManageHR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ManageHR` DEFAULT CHARACTER SET utf8 ;
USE `db_ManageHR` ;

-- -----------------------------------------------------
-- Table `db_ManageHR`.`Paz_y_salvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Paz_y_salvo` (
  `d_paz_salvo` INT NOT NULL AUTO_INCREMENT,
  `descrip` TEXT NULL,
  `firma` VARCHAR(45) NULL,
  PRIMARY KEY (`d_paz_salvo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Vacaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Vacaciones` (
  `id_incapacidad` INT NOT NULL AUTO_INCREMENT,
  `descrip` TEXT NULL,
  `archivo` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_final` DATE NULL,
  PRIMARY KEY (`id_incapacidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Incapacidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Incapacidad` (
  `id_incapacidad` INT NOT NULL AUTO_INCREMENT,
  `descrip` TEXT NULL,
  `archivo` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_final` DATE NULL,
  PRIMARY KEY (`id_incapacidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Horas_Extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Horas_Extras` (
  `id_Horas_Extras` INT NOT NULL AUTO_INCREMENT,
  `descrip` TEXT(500) NULL,
  `fecha` DATE NULL,
  `n_horas_extra` INT NULL,
  `tipo_horas` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Horas_Extras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`hoja_vida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`hoja_vida` (
  `id_hoja_de_vida` INT NOT NULL AUTO_INCREMENT,
  `estado_civil` VARCHAR(45) NULL,
  `ref_personal` VARCHAR(45) NULL,
  `ref_laboral` VARCHAR(45) NULL,
  `tel_ref_personal` VARCHAR(45) NULL,
  `tel_ref_laboral` VARCHAR(45) NULL,
  `descripcion_personal` TEXT NULL,
  `descripcion_laboral` TEXT NULL,
  `fecha_nacimiento` DATE NULL,
  `clase_libreta_militar` VARCHAR(45) NULL,
  `numero_libreta_militar` VARCHAR(45) NULL,
  `documento_identidad` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  PRIMARY KEY (`id_hoja_de_vida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Registro` (
  `numero_documento` INT NOT NULL,
  `primer_nombre` VARCHAR(45) NOT NULL,
  `segundo_nombre` VARCHAR(45) NOT NULL,
  `s_nombre` VARCHAR(45) NOT NULL,
  `primer_apellido` VARCHAR(100) NOT NULL,
  `segundo_apellido` VARCHAR(100) NOT NULL,
  `clave` VARCHAR(45) NULL,
  `confir_clave` VARCHAR(45) NULL,
  `pensiones` VARCHAR(45) NULL,
  `eps` VARCHAR(45) NULL,
  `fecha_nac` DATE NOT NULL,
  `lugar_nac` VARCHAR(45) NOT NULL,
  `n_hijos` INT NULL,
  `emer_nom` VARCHAR(45) NULL,
  `emer_contact` INT NULL,
  `correo` VARCHAR(45) NULL,
  `confir_correo` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `tel` INT NOT NULL,
  `tipo_documento` VARCHAR(15) NULL,
  `Paz_y_salvo_d_paz_salvo` INT NOT NULL,
  `Vacaciones_id_incapacidad` INT NOT NULL,
  `Incapacidad_id_incapacidad` INT NOT NULL,
  `Horas_Extras_id_Horas_Extras` INT NOT NULL,
  `hoja_vida_id_hoja_de_vida` INT NOT NULL,
  PRIMARY KEY (`numero_documento`),
  INDEX `fk_Registro_Paz_y_salvo1_idx` (`Paz_y_salvo_d_paz_salvo` ASC) ,
  INDEX `fk_Registro_Vacaciones1_idx` (`Vacaciones_id_incapacidad` ASC) ,
  INDEX `fk_Registro_Incapacidad1_idx` (`Incapacidad_id_incapacidad` ASC) ,
  INDEX `fk_Registro_Horas_Extras1_idx` (`Horas_Extras_id_Horas_Extras` ASC) ,
  INDEX `fk_Registro_hoja_vida1_idx` (`hoja_vida_id_hoja_de_vida` ASC) ,
  CONSTRAINT `fk_Registro_Paz_y_salvo1`
    FOREIGN KEY (`Paz_y_salvo_d_paz_salvo`)
    REFERENCES `db_ManageHR`.`Paz_y_salvo` (`d_paz_salvo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Vacaciones1`
    FOREIGN KEY (`Vacaciones_id_incapacidad`)
    REFERENCES `db_ManageHR`.`Vacaciones` (`id_incapacidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Incapacidad1`
    FOREIGN KEY (`Incapacidad_id_incapacidad`)
    REFERENCES `db_ManageHR`.`Incapacidad` (`id_incapacidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Horas_Extras1`
    FOREIGN KEY (`Horas_Extras_id_Horas_Extras`)
    REFERENCES `db_ManageHR`.`Horas_Extras` (`id_Horas_Extras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_hoja_vida1`
    FOREIGN KEY (`hoja_vida_id_hoja_de_vida`)
    REFERENCES `db_ManageHR`.`hoja_vida` (`id_hoja_de_vida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Categoria_vacantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Categoria_vacantes` (
  `id_cat_vac` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cat_vac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Profesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Profesion` (
  `id_profesion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `Categoria_vacantes_id_cat_vac` INT NOT NULL,
  PRIMARY KEY (`id_profesion`),
  INDEX `fk_Profesion_Categoria_vacantes1_idx` (`Categoria_vacantes_id_cat_vac` ASC) ,
  CONSTRAINT `fk_Profesion_Categoria_vacantes1`
    FOREIGN KEY (`Categoria_vacantes_id_cat_vac`)
    REFERENCES `db_ManageHR`.`Categoria_vacantes` (`id_cat_vac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Vacantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Vacantes` (
  `id_vacantes` INT NOT NULL AUTO_INCREMENT,
  `nombre_vac` VARCHAR(45) NULL,
  `descrip_vac` VARCHAR(45) NULL,
  `salario` FLOAT NULL,
  `exper_min` VARCHAR(45) NULL,
  `cargo_vac` VARCHAR(45) NULL,
  `Profesion_id_profesion` INT NOT NULL,
  PRIMARY KEY (`id_vacantes`),
  INDEX `fk_Vacantes_Profesion1_idx` (`Profesion_id_profesion` ASC) ,
  CONSTRAINT `fk_Vacantes_Profesion1`
    FOREIGN KEY (`Profesion_id_profesion`)
    REFERENCES `db_ManageHR`.`Profesion` (`id_profesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`experiencia_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`experiencia_laboral` (
  `id_experiencia` INT NOT NULL AUTO_INCREMENT,
  `nom_empresa` VARCHAR(45) NULL,
  `nom_jefe` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `cargo` VARCHAR(45) NULL,
  `tipo_docum` VARCHAR(45) NULL,
  `actividades` TEXT NULL,
  `experiencia_laboral` VARCHAR(45) NULL,
  `certificado` VARCHAR(45) NULL,
  `hoja_vida_id_hoja_de_vida` INT NOT NULL,
  PRIMARY KEY (`id_experiencia`),
  INDEX `fk_experiencia_laboral_hoja_vida1_idx` (`hoja_vida_id_hoja_de_vida` ASC) ,
  CONSTRAINT `fk_experiencia_laboral_hoja_vida1`
    FOREIGN KEY (`hoja_vida_id_hoja_de_vida`)
    REFERENCES `db_ManageHR`.`hoja_vida` (`id_hoja_de_vida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`estudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`estudios` (
  `id_estudios` INT NOT NULL AUTO_INCREMENT,
  `nom_inst` VARCHAR(45) NULL,
  `nom_estudio` VARCHAR(45) NULL,
  `primer_nombre` VARCHAR(45) NULL,
  `titulo_obtenido` VARCHAR(45) NULL,
  `año_estudio` VARCHAR(45) NULL,
  `hoja_vida_id_hoja_de_vida` INT NOT NULL,
  PRIMARY KEY (`id_estudios`),
  INDEX `fk_estudios_hoja_vida1_idx` (`hoja_vida_id_hoja_de_vida` ASC) ,
  CONSTRAINT `fk_estudios_hoja_vida1`
    FOREIGN KEY (`hoja_vida_id_hoja_de_vida`)
    REFERENCES `db_ManageHR`.`hoja_vida` (`id_hoja_de_vida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Postulaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Postulaciones` (
  `idPostulaciones` INT NOT NULL AUTO_INCREMENT,
  `nombre_vacante` VARCHAR(45) NULL,
  PRIMARY KEY (`idPostulaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Rol_has_Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Rol_has_Registro` (
  `Rol_id_rol` INT NOT NULL,
  `Registro_id_registro` INT NOT NULL,
  PRIMARY KEY (`Rol_id_rol`, `Registro_id_registro`),
  INDEX `fk_Rol_has_Registro_Registro1_idx` (`Registro_id_registro` ASC) ,
  INDEX `fk_Rol_has_Registro_Rol1_idx` (`Rol_id_rol` ASC) ,
  CONSTRAINT `fk_Rol_has_Registro_Rol1`
    FOREIGN KEY (`Rol_id_rol`)
    REFERENCES `db_ManageHR`.`Rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rol_has_Registro_Registro1`
    FOREIGN KEY (`Registro_id_registro`)
    REFERENCES `db_ManageHR`.`Registro` (`numero_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Vacantes_has_Postulaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Vacantes_has_Postulaciones` (
  `Vacantes_id_vacantes` INT NOT NULL,
  `Postulaciones_idPostulaciones` INT NOT NULL,
  PRIMARY KEY (`Vacantes_id_vacantes`, `Postulaciones_idPostulaciones`),
  INDEX `fk_Vacantes_has_Postulaciones_Postulaciones1_idx` (`Postulaciones_idPostulaciones` ASC) ,
  INDEX `fk_Vacantes_has_Postulaciones_Vacantes1_idx` (`Vacantes_id_vacantes` ASC) ,
  CONSTRAINT `fk_Vacantes_has_Postulaciones_Vacantes1`
    FOREIGN KEY (`Vacantes_id_vacantes`)
    REFERENCES `db_ManageHR`.`Vacantes` (`id_vacantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vacantes_has_Postulaciones_Postulaciones1`
    FOREIGN KEY (`Postulaciones_idPostulaciones`)
    REFERENCES `db_ManageHR`.`Postulaciones` (`idPostulaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Categoria_vacantes_has_hoja_vida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Categoria_vacantes_has_hoja_vida` (
  `Categoria_vacantes_id_cat_vac` INT NOT NULL,
  `hoja_vida_id_hoja_de_vida` INT NOT NULL,
  PRIMARY KEY (`Categoria_vacantes_id_cat_vac`, `hoja_vida_id_hoja_de_vida`),
  INDEX `fk_Categoria_vacantes_has_hoja_vida_hoja_vida1_idx` (`hoja_vida_id_hoja_de_vida` ASC) ,
  INDEX `fk_Categoria_vacantes_has_hoja_vida_Categoria_vacantes1_idx` (`Categoria_vacantes_id_cat_vac` ASC) ,
  CONSTRAINT `fk_Categoria_vacantes_has_hoja_vida_Categoria_vacantes1`
    FOREIGN KEY (`Categoria_vacantes_id_cat_vac`)
    REFERENCES `db_ManageHR`.`Categoria_vacantes` (`id_cat_vac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_vacantes_has_hoja_vida_hoja_vida1`
    FOREIGN KEY (`hoja_vida_id_hoja_de_vida`)
    REFERENCES `db_ManageHR`.`hoja_vida` (`id_hoja_de_vida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ManageHR`.`Categoria_vacantes_has_Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ManageHR`.`Categoria_vacantes_has_Registro` (
  `Categoria_vacantes_id_cat_vac` INT NOT NULL,
  `Registro_numero_documento` INT NOT NULL,
  PRIMARY KEY (`Categoria_vacantes_id_cat_vac`, `Registro_numero_documento`),
  INDEX `fk_Categoria_vacantes_has_Registro_Registro1_idx` (`Registro_numero_documento` ASC) ,
  INDEX `fk_Categoria_vacantes_has_Registro_Categoria_vacantes1_idx` (`Categoria_vacantes_id_cat_vac` ASC) ,
  CONSTRAINT `fk_Categoria_vacantes_has_Registro_Categoria_vacantes1`
    FOREIGN KEY (`Categoria_vacantes_id_cat_vac`)
    REFERENCES `db_ManageHR`.`Categoria_vacantes` (`id_cat_vac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_vacantes_has_Registro_Registro1`
    FOREIGN KEY (`Registro_numero_documento`)
    REFERENCES `db_ManageHR`.`Registro` (`numero_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
